// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignCatalogRole(arg1, arg2, arg3) {
  return window['go']['wails']['Bridge']['AssignCatalogRole'](arg1, arg2, arg3);
}

export function ClearNotifications() {
  return window['go']['wails']['Bridge']['ClearNotifications']();
}

export function ConfigureProvider(arg1, arg2) {
  return window['go']['wails']['Bridge']['ConfigureProvider'](arg1, arg2);
}

export function ConnectProvider(arg1, arg2) {
  return window['go']['wails']['Bridge']['ConnectProvider'](arg1, arg2);
}

export function CreateConversation(arg1, arg2) {
  return window['go']['wails']['Bridge']['CreateConversation'](arg1, arg2);
}

export function CreateNotification(arg1) {
  return window['go']['wails']['Bridge']['CreateNotification'](arg1);
}

export function DeleteCatalogRole(arg1) {
  return window['go']['wails']['Bridge']['DeleteCatalogRole'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['wails']['Bridge']['DeleteConversation'](arg1);
}

export function DeleteNotification(arg1) {
  return window['go']['wails']['Bridge']['DeleteNotification'](arg1);
}

export function DisconnectProvider(arg1) {
  return window['go']['wails']['Bridge']['DisconnectProvider'](arg1);
}

export function EditImage(arg1) {
  return window['go']['wails']['Bridge']['EditImage'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['wails']['Bridge']['GenerateImage'](arg1);
}

export function GetActiveConversation() {
  return window['go']['wails']['Bridge']['GetActiveConversation']();
}

export function GetActiveProvider() {
  return window['go']['wails']['Bridge']['GetActiveProvider']();
}

export function GetCatalogOverview() {
  return window['go']['wails']['Bridge']['GetCatalogOverview']();
}

export function GetConversation(arg1) {
  return window['go']['wails']['Bridge']['GetConversation'](arg1);
}

export function GetProviders() {
  return window['go']['wails']['Bridge']['GetProviders']();
}

export function ImportModels(arg1) {
  return window['go']['wails']['Bridge']['ImportModels'](arg1);
}

export function ListConversations() {
  return window['go']['wails']['Bridge']['ListConversations']();
}

export function ListDeletedConversations() {
  return window['go']['wails']['Bridge']['ListDeletedConversations']();
}

export function ListModels(arg1) {
  return window['go']['wails']['Bridge']['ListModels'](arg1);
}

export function ListNotifications() {
  return window['go']['wails']['Bridge']['ListNotifications']();
}

export function PurgeConversation(arg1) {
  return window['go']['wails']['Bridge']['PurgeConversation'](arg1);
}

export function QueryModels(arg1) {
  return window['go']['wails']['Bridge']['QueryModels'](arg1);
}

export function RefreshCatalogEndpoint(arg1) {
  return window['go']['wails']['Bridge']['RefreshCatalogEndpoint'](arg1);
}

export function RefreshProviderResources(arg1) {
  return window['go']['wails']['Bridge']['RefreshProviderResources'](arg1);
}

export function RestoreConversation(arg1) {
  return window['go']['wails']['Bridge']['RestoreConversation'](arg1);
}

export function SaveCatalogRole(arg1) {
  return window['go']['wails']['Bridge']['SaveCatalogRole'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['wails']['Bridge']['SendMessage'](arg1, arg2);
}

export function SetActiveConversation(arg1) {
  return window['go']['wails']['Bridge']['SetActiveConversation'](arg1);
}

export function SetActiveProvider(arg1) {
  return window['go']['wails']['Bridge']['SetActiveProvider'](arg1);
}

export function StopStream() {
  return window['go']['wails']['Bridge']['StopStream']();
}

export function SyncModels() {
  return window['go']['wails']['Bridge']['SyncModels']();
}

export function TestCatalogEndpoint(arg1) {
  return window['go']['wails']['Bridge']['TestCatalogEndpoint'](arg1);
}

export function TestProvider(arg1) {
  return window['go']['wails']['Bridge']['TestProvider'](arg1);
}

export function UnassignCatalogRole(arg1, arg2) {
  return window['go']['wails']['Bridge']['UnassignCatalogRole'](arg1, arg2);
}

export function UpdateConversationModel(arg1, arg2) {
  return window['go']['wails']['Bridge']['UpdateConversationModel'](arg1, arg2);
}

export function UpdateConversationProvider(arg1, arg2) {
  return window['go']['wails']['Bridge']['UpdateConversationProvider'](arg1, arg2);
}
