// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureProvider(arg1, arg2) {
  return window['go']['wails']['Bridge']['ConfigureProvider'](arg1, arg2);
}

export function ConnectProvider(arg1, arg2) {
  return window['go']['wails']['Bridge']['ConnectProvider'](arg1, arg2);
}

export function CreateConversation(arg1, arg2) {
  return window['go']['wails']['Bridge']['CreateConversation'](arg1, arg2);
}

export function CreateNotification(arg1) {
  return window['go']['wails']['Bridge']['CreateNotification'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['wails']['Bridge']['DeleteConversation'](arg1);
}

export function DisconnectProvider(arg1) {
  return window['go']['wails']['Bridge']['DisconnectProvider'](arg1);
}

export function GetActiveConversation() {
  return window['go']['wails']['Bridge']['GetActiveConversation']();
}

export function GetActiveProvider() {
  return window['go']['wails']['Bridge']['GetActiveProvider']();
}

export function GetConversation(arg1) {
  return window['go']['wails']['Bridge']['GetConversation'](arg1);
}

export function GetProviders() {
  return window['go']['wails']['Bridge']['GetProviders']();
}

export function ListConversations() {
  return window['go']['wails']['Bridge']['ListConversations']();
}

export function ListDeletedConversations() {
  return window['go']['wails']['Bridge']['ListDeletedConversations']();
}

export function ListNotifications() {
  return window['go']['wails']['Bridge']['ListNotifications']();
}

export function PurgeConversation(arg1) {
  return window['go']['wails']['Bridge']['PurgeConversation'](arg1);
}

export function RefreshProviderResources(arg1) {
  return window['go']['wails']['Bridge']['RefreshProviderResources'](arg1);
}

export function RestoreConversation(arg1) {
  return window['go']['wails']['Bridge']['RestoreConversation'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['wails']['Bridge']['SendMessage'](arg1, arg2);
}

export function SetActiveConversation(arg1) {
  return window['go']['wails']['Bridge']['SetActiveConversation'](arg1);
}

export function SetActiveProvider(arg1) {
  return window['go']['wails']['Bridge']['SetActiveProvider'](arg1);
}

export function StopStream() {
  return window['go']['wails']['Bridge']['StopStream']();
}

export function TestProvider(arg1) {
  return window['go']['wails']['Bridge']['TestProvider'](arg1);
}

export function UpdateConversationModel(arg1, arg2) {
  return window['go']['wails']['Bridge']['UpdateConversationModel'](arg1, arg2);
}

export function UpdateConversationProvider(arg1, arg2) {
  return window['go']['wails']['Bridge']['UpdateConversationProvider'](arg1, arg2);
}
