// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {provider} from '../models';
import {chat} from '../models';

export function ConfigureProvider(arg1:string,arg2:string):Promise<void>;

export function ConnectProvider(arg1:string,arg2:string):Promise<provider.Info>;

export function CreateConversation(arg1:string,arg2:string):Promise<chat.Conversation>;

export function DeleteConversation(arg1:string):Promise<boolean>;

export function DisconnectProvider(arg1:string):Promise<void>;

export function GetActiveConversation():Promise<chat.Conversation>;

export function GetActiveProvider():Promise<provider.Info>;

export function GetConversation(arg1:string):Promise<chat.Conversation>;

export function GetProviders():Promise<Array<provider.Info>>;

export function ListConversations():Promise<Array<chat.ConversationSummary>>;

export function ListDeletedConversations():Promise<Array<chat.ConversationSummary>>;

export function PurgeConversation(arg1:string):Promise<boolean>;

export function RefreshProviderResources(arg1:string):Promise<void>;

export function RestoreConversation(arg1:string):Promise<boolean>;

export function SendMessage(arg1:string,arg2:string):Promise<chat.Message>;

export function SetActiveConversation(arg1:string):Promise<void>;

export function SetActiveProvider(arg1:string):Promise<boolean>;

export function StopStream():Promise<void>;

export function TestProvider(arg1:string):Promise<void>;

export function UpdateConversationModel(arg1:string,arg2:string):Promise<boolean>;
