// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {core} from '../models';
import {provider} from '../models';
import {domain} from '../models';
import {notifications} from '../models';
import {interfaces} from '../models';

export function AssignCatalogRole(arg1:string,arg2:string,arg3:string):Promise<catalog.RoleAssignmentResult>;

export function ClearNotifications():Promise<boolean>;

export function ConfigureProvider(arg1:string,arg2:core.ProviderCredentials):Promise<void>;

export function ConnectProvider(arg1:string,arg2:core.ProviderCredentials):Promise<provider.Info>;

export function CreateConversation(arg1:string,arg2:string):Promise<domain.Conversation>;

export function CreateNotification(arg1:notifications.NotificationPayload):Promise<domain.Notification>;

export function DeleteCatalogRole(arg1:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<boolean>;

export function DeleteNotification(arg1:number):Promise<boolean>;

export function DisconnectProvider(arg1:string):Promise<void>;

export function EditImage(arg1:interfaces.EditImageRequest):Promise<interfaces.ImageBinaryResult>;

export function GenerateImage(arg1:interfaces.GenerateImageRequest):Promise<interfaces.ImageBinaryResult>;

export function GetActiveConversation():Promise<domain.Conversation>;

export function GetActiveProvider():Promise<provider.Info>;

export function GetCatalogOverview():Promise<catalog.CatalogOverview>;

export function GetConversation(arg1:string):Promise<domain.Conversation>;

export function GetProviders():Promise<Array<provider.Info>>;

export function ImportModels(arg1:string):Promise<void>;

export function ListConversations():Promise<Array<domain.ConversationSummary>>;

export function ListDeletedConversations():Promise<Array<domain.ConversationSummary>>;

export function ListModels(arg1:string):Promise<Array<interfaces.ModelSummary>>;

export function ListNotifications():Promise<Array<domain.Notification>>;

export function PurgeConversation(arg1:string):Promise<boolean>;

export function QueryModels(arg1:interfaces.ModelListFilter):Promise<Array<interfaces.ModelSummary>>;

export function RefreshCatalogEndpoint(arg1:string):Promise<void>;

export function RefreshProviderResources(arg1:string):Promise<void>;

export function RestoreConversation(arg1:string):Promise<boolean>;

export function SaveCatalogRole(arg1:catalog.RoleSummary):Promise<catalog.RoleSummary>;

export function SendMessage(arg1:string,arg2:string):Promise<domain.Message>;

export function SetActiveConversation(arg1:string):Promise<void>;

export function SetActiveProvider(arg1:string):Promise<boolean>;

export function StopStream():Promise<void>;

export function SyncModels():Promise<interfaces.SyncModelsResult>;

export function TestCatalogEndpoint(arg1:string):Promise<void>;

export function TestProvider(arg1:string):Promise<void>;

export function UnassignCatalogRole(arg1:string,arg2:string):Promise<void>;

export function UpdateConversationModel(arg1:string,arg2:string):Promise<boolean>;

export function UpdateConversationProvider(arg1:string,arg2:string):Promise<boolean>;
